// Generated by CoffeeScript 1.12.5
(function() {
  window.Dungeon = {
    generate: function() {
      var i, j, params, value;
      params = {
        seed: byId('seed').value,
        width: byId('width').value,
        height: byId('height').value,
        tileSize: byId('tile-size').value,
        initialDensity: byId('initial-density').value,
        reseedDensity: byId('reseed-density').value,
        smoothCorners: byId('smooth').checked,
        reseedMethod: byId('reseed-method').value,
        emptyTolerance: byId('empty-tolerance').value,
        wallRoughness: byId('wall-roughness').value,
        passes: []
      };
      for (i = j = 1; j <= 6; i = ++j) {
        value = byId('pass-' + i).value;
        if (value !== '') {
          params.passes.push(value);
        }
      }
      console.log(params.passes);
      byId('params').innerHTML = JSON.stringify(params);
      window.randSeed = seed;
      this.map = new Map('map', params);
      this.zoom();
      return this.map.draw();
    },
    randomSeed: function() {
      return byId('seed').value = Math.floor(Math.random() * 1000000);
    },
    zoom: function() {
      return this.map.canvas.style.width = this.map.canvas.width * parseFloat(byId('zoom').value) + 'px';
    }
  };

}).call(this);
