// Generated by CoffeeScript 1.12.5
(function() {
  var Tween;

  Tween = (function() {
    function Tween(time, elements) {
      this.time = time;
      this.elements = elements;
      this.running = true;
      this.timePassed = 0;
      this.update(0);
    }

    Tween.prototype.update = function(delta) {
      var k, multiplier, ref, results, v;
      if (!this.running) {
        return false;
      }
      this.timePassed += delta;
      if (this.timePassed > this.time) {
        multiplier = 1;
        this.running = false;
      } else {
        multiplier = this.timePassed / this.time;
      }
      ref = this.elements;
      results = [];
      for (k in ref) {
        v = ref[k];
        results.push(v[2] = (v[1] - v[0]) * multiplier + v[0]);
      }
      return results;
    };

    Tween.prototype.value = function(name) {
      return this.elements[name][2];
    };

    Tween.prototype.changeValue = function(name, value) {
      this.elements[name][1] += value;
      return this.running = true;
    };

    return Tween;

  })();

  window.Tween = Tween;

}).call(this);
