// Generated by CoffeeScript 1.12.5
(function() {
  window.Vectors = {
    addVectorToPoint: function(point, angRad, length) {
      var newPoint;
      newPoint = {
        x: 0,
        y: 0
      };
      newPoint.x = point.x + (Math.cos(angRad) * length);
      newPoint.y = point.y + (Math.sin(angRad) * length);
      return newPoint;
    },
    angleDistBetweenPoints: function(fromPoint, toPoint) {
      var angle, distance, x, y;
      if (fromPoint === toPoint) {
        return 0;
      }
      x = toPoint.x - fromPoint.x;
      y = toPoint.y - fromPoint.y;
      distance = Math.sqrt(x * x + y * y);
      angle = Math.acos(x / distance);
      if (y < 0) {
        angle = 0 - angle;
      }
      return {
        angle: angle,
        distance: distance
      };
    }
  };

}).call(this);
